"""
Candidate Profile

This file represents the candidate and is used across the scoring,
recruiting, and personalization layers.
"""

from dataclasses import dataclass, field


@dataclass(slots=True)
class CandidateProfile:
    # Basic Information
    name: str
    experience_level: str
    email: str
    portfolio: str
    github: str
    linkedin: str
    summary: str

    # Job Preferences
    remote_only: bool = True
    preferred_roles: list[str] = field(default_factory=list)
    preferred_skills: list[str] = field(default_factory=list)
    preferred_countries: list[str] = field(default_factory=list)
    excluded_titles: list[str] = field(default_factory=list)
    target_title_keywords: list[str] = field(default_factory=list)
    prefilter_excluded_keywords: list[str] = field(default_factory=list)
    strong_title_keywords: list[str] = field(default_factory=list)
    discouraged_title_keywords: list[str] = field(default_factory=list)
    junior_title_keywords: list[str] = field(default_factory=list)
    minimum_score: int = 55


MY_PROFILE = CandidateProfile(
    name="V Cyril Darivs Egipto",
    experience_level="Junior Full-Stack Software Engineer & Technical Support Specialist",
    email="darivsxp@gmail.com",
    portfolio="https://www.cyrilegipto.space/",
    github="https://github.com/DarivsXP",
    linkedin="https://linkedin.com/v-cyril",
    summary=(
        "Junior Full-Stack Developer experienced in building scalable web applications, "
        "resolving complex technical issues, and delivering customer-focused solutions. "
        "Proficient in Laravel, React, Vue.js, PHP, Python, and MySQL."
    ),
    remote_only=True,
    preferred_roles=[
        "Junior Software Engineer",
        "Junior Backend Developer",
        "Backend Developer",
        "Junior Full Stack Developer",
        "Laravel Developer",
        "PHP Developer",
        "Software Developer",
        "Technical Support Engineer",
        "Application Support Engineer",
        "Junior Full-Stack Software Engineer",
        "Junior Full-Stack Developer",
        "Junior Full Stack Engineer",
        "Full Stack Developer",
        "Full Stack Engineer",
        "Full-Stack Developer",
        "Full-Stack Engineer",
        "Vue Developer",
        "Vue.js Developer",
        "React Developer",
        "React.js Developer",
        "Software Engineer",
        "Web Developer",
        "Frontend Developer",
        "Frontend Engineer",
        "Python Developer",
        "Python Engineer",
        "Support Engineer",
        "Associate Software Engineer",
        "Associate Developer",
        "Technical Support Representative",
        "IT Support Specialist",
        "Technical Support Specialist",
        "Customer Support Engineer",
        "Support Developer",
    ],
    preferred_skills=[
        "PHP",
        "Laravel",
        "Python",
        "JavaScript",
        "HTML",
        "CSS",
        "MySQL",
        "PostgreSQL",
        "SQLite",
        "Git",
        "GitHub",
        "REST API",
        "REST",
        "JSON",
        "API",
        "Vue.js",
        "Vue",
        "React.js",
        "React",
        "TypeScript",
        "Node.js",
        "Tailwind CSS",
        "Docker",
        "Bootstrap",
        "Linux",
        "Bash",
        "DNS",
        "SSL",
        "cPanel",
        "WordPress",
        "C++",
        "C",
    ],
    preferred_countries=[
        # Tier 1 — preferred regions
        "Australia",
        "AUS",
        "Canada",
        "CA",
        "United Kingdom",
        "UK",
        "Singapore",
        "New Zealand",
        "NZ",
        # Tier 2 — open to remote from anywhere
        "Worldwide",
        "Remote",
        "Global",
        "Anywhere",
        "USA",
        "United States",
        "US",
        "Europe",
        "European Union",
        "EU",
        # Asia Pacific — PH, India, and broader Asia
        "Philippines",
        "PH",
        "India",
        "IN",
        "Asia",
        "South Asia",
        "Southeast Asia",
        "East Asia",
        "APAC",
        "Asia Pacific",
        "Japan",
        "Malaysia",
        "Indonesia",
        "Taiwan",
        "South Korea",
        "Vietnam",
        "Thailand",
        "Hong Kong",
        "Bangladesh",
        "Pakistan",
        "Sri Lanka",
        # Rest of world
        "Latin America",
        "LATAM",
        "EMEA",
        "Oceania",
        "Americas",
        "EST",
        "PST",
        "CST",
        "CET",
        "GMT",
    ],
    excluded_titles=[
        "Senior",
        "Sr.",
        "Sr ",
        "Staff",
        "Principal",
        "Lead",
        "Architect",
        "Manager",
        "Director",
        "Head",
        "VP",
        "Expert",
        "Mid-Senior",
        "Mid-level",
    ],
    target_title_keywords=[
        "backend",
        "software engineer",
        "software developer",
        "developer",
        "engineer",
        "full stack",
        "full-stack",
        "php",
        "laravel",
        "python",
        "web developer",
        "application support",
        "technical support engineer",
        "support engineer",
        "technical support",
        "support specialist",
        "tier 2 support",
        "customer support engineer",
        "intern",
        "react",
        "vue",
        "typescript",
        "fullstack",
    ],
    prefilter_excluded_keywords=[
        # Non-tech roles — keep specific to avoid false positives
        "account manager",
        "accountant",
        "data analyst",
        "business analyst",
        "financial analyst",
        "executive assistant",
        "administrative assistant",
        "bookkeeper",
        "care advocate",
        "client success manager",
        "content creator",
        "copywriter",
        "creative director",
        "customer happiness",
        "data entry",
        "graphic designer",
        "ux designer",
        "ui designer",
        "freelance writer",
        "human resources",
        "hr manager",
        "hr specialist",
        "illustrator",
        "marketing manager",
        "marketing specialist",
        "medical",
        "nurse",
        "operations manager",
        "patient",
        "product manager",
        "project manager",
        "qa lead",
        "recruiter",
        "talent acquisition",
        "sales representative",
        "sales manager",
        "account executive",
        "secretary",
        "social media manager",
        "speculative application",
        "test job",
        "freelance writer",
        "technical writer",
        "scrum master",
        "agile coach",
        "mid-level",
        "mid level",
        "midlevel",
        "intermediate",
    ],
    strong_title_keywords=[
        "backend",
        "php",
        "laravel",
        "application support",
        "technical support",
        "support engineer",
        "support specialist",
        "tier 2 support",
        "customer support engineer",
        "full stack",
        "full-stack",
        "software engineer",
        "web development intern",
        "full-stack developer",
        "full-stack engineer",
        "fullstack developer",
        "fullstack engineer",
        "vue developer",
        "react developer",
        "junior full-stack",
        "junior full stack",
        # Additional strong signals for Cyril's background
        "application specialist",
        "it support",
        "service desk",
        "helpdesk",
        "help desk",
        "technical analyst",
        "cms developer",
        "web application",
        "junior developer",
        "junior engineer",
        "junior web",
        "graduate developer",
        "graduate engineer",
    ],
    discouraged_title_keywords=[
        "devops",
        "platform engineer",
        "site reliability",
        "sre",
        "react native",
        "ios",
        "penetration tester",
        "security",
        "designer",
        "qa",
        "quality assurance",
        "data analyst",
        "business analyst",
    ],
    junior_title_keywords=[
        "junior",
        "jr",
        "graduate",
        "entry",
        "entry-level",
        "new grad",
        "associate",
        "intern",
        "internship",
        "trainee",
        "apprenticeship",
        "fresh graduate",
        "0-2 years",
        "no experience",
    ],
    minimum_score=35,
)

